base_model: mistralai/Mistral-7B-v0.1
base_model_config: mistralai/Mistral-7B-v0.1
model_type: MistralForCausalLM
tokenizer_type: LlamaTokenizer
is_mistral_derived_model: true

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: code_instructions_122k_alpaca_style/code_instructions_120k.json
    type: alpaca
dataset_prepared_path:
val_set_size: 0.01
output_dir: ./mistral_coder_5e-6_medusa_5heads_0.02_0.8

sequence_len: 8192
sample_packing: true
pad_to_sequence_len: true

wandb_project: mistral_coder_v1
wandb_entity:
wandb_watch:
wandb_run_id:
wandb_log_model:

gradient_accumulation_steps: 2
micro_batch_size: 4
num_epochs: 3
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.000005

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps:
warmup_ratio: 0.05
eval_steps: 20
save_steps:
save_total_limit: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"

medusa_num_heads: 5
medusa_num_layers: 0
medusa_heads_coefficient: 0.02
medusa_decay_coefficient: 0.8
medusa_logging: true
