base_model: lmsys/vicuna-7b-v1.5
base_model_config: lmsys/vicuna-7b-v1.5
model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizer
is_llama_derived_model: true

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: ShareGPT_Vicuna_unfiltered/ShareGPT_V4.3_unfiltered_cleaned_split.json
    type: sharegpt
dataset_prepared_path:
val_set_size: 0.01
output_dir: ./vicuna_only_head_lr_1e-3_medusa_5_1_1.0_0.8_constant_2

sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true

wandb_project: medusa_vicuna_1.5_v1
wandb_entity:
wandb_watch:
wandb_run_id:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 4
num_epochs: 3
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.001

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: false
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 20
eval_steps: 20
save_steps:
save_total_limit: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"

medusa_num_heads: 5
medusa_num_layers: 1
medusa_heads_coefficient: 1.0
medusa_decay_coefficient: 0.8
medusa_logging: true
medusa_scheduler: constant
medusa_only_heads: true
medusa_num_unfreeze_layers: 2
medusa_lr_multiplier: 1.0
