####
base_model: /models/mistral-100M
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  ####
  - path: /root/work/chat-regen/instructions/saiga-nemo-12b/test-novita-20250121.local.jsonl
    type: alpaca_chat.load_concise
dataset_prepared_path:

dataset_prepared_path:
val_set_size: 0.001
####
output_dir: /models/train/test-mistral-100m-finetune
auto_resume_from_checkpoints: true

sequence_len: 2048
sample_packing: false
pad_to_sequence_len: true

unfrozen_parameters:
  - model.embed_tokens.
  - model.layers.3.
  - lm_head.

wandb_project: mistral
wandb_entity: k-l-lambda-org
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 4
####
max_steps: 1000
####
micro_batch_size: 1
####
num_epochs: 1
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true
s2_attention:

warmup_steps: 10
evals_per_epoch: 4
eval_table_size:
eval_max_new_tokens: 128
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
