base_model: /models/Llama-3.2-100M
model_type: LlamaForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: /root/work/chat-regen/chat/llama3.1-8b-instruct/chat-10k.jsonl
    type: sharegpt.load_ultrachat
dataset_prepared_path:

dataset_prepared_path:
val_set_size: 0.05
output_dir: ./outputs/100m-v2

sequence_len: 4096
sample_packing: false
pad_to_sequence_len: true

unfrozen_parameters:
  - model.embed_tokens.
  - model.layers.3.
  - model.norm.

wandb_project: llama3
wandb_entity: k-l-lambda-org
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 1
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true
s2_attention:

warmup_steps: 10
evals_per_epoch: 4
eval_table_size:
eval_max_new_tokens: 128
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<|begin_of_text|>"
  eos_token: "<|end_of_text|>"
  pad_token: "<|end_of_text|>"

teacher_distill:
  model_id: meta-llama/Meta-Llama-3.1-8B-Instruct
  loss_coefficient: 0.1
