base_model: /network/models/Llama-3.2-100M-init
model_type: LlamaForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: false
strict: false

max_steps: 500000
pretraining_dataset:
  - path: allenai/c4
    type: pretrain
    name: en

dataset_prepared_path:
val_set_size: 0.05
output_dir: /network/train/llama3/20241126-llama3.2-100M-pretrain

sequence_len: 8192
sample_packing: True
pad_to_sequence_len: true

wandb_project: llama3
wandb_entity: k-l-lambda-org
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 1
micro_batch_size: 1
num_epochs: 100
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true
s2_attention:

warmup_steps: 10
#evals_per_epoch: 4
#eval_table_size:
#eval_max_new_tokens: 128
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<|begin_of_text|>"
  eos_token: "<|end_of_text|>"
  pad_token: "<|end_of_text|>"
