base_model: /root/work/Llama-3.2-200M
model_type: LlamaForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: /root/work/chat-regen/chat/llama3.1-8b-instruct/business-10k.jsonl
    type: sharegpt.load_ultrachat
  - path: /root/work/chat-regen/chat/llama3.1-8b-instruct/chat-10k.jsonl
    type: sharegpt.load_ultrachat
  - path: /root/work/chat-regen/chat/llama3.1-8b-instruct/education-10k.jsonl
    type: sharegpt.load_ultrachat
  - path: /root/work/chat-regen/chat/llama3.1-8b-instruct/health-10k.jsonl
    type: sharegpt.load_ultrachat
  - path: /root/work/chat-regen/chat/llama3.1-8b-instruct/knowledge-10k.jsonl
    type: sharegpt.load_ultrachat
  - path: /root/work/chat-regen/chat/llama3.1-8b-instruct/programming-10k.jsonl
    type: sharegpt.load_ultrachat
  - path: /root/work/chat-regen/chat/llama3.1-8b-instruct/support-10k.jsonl
    type: sharegpt.load_ultrachat
  - path: /root/work/chat-regen/chat/llama3.1-8b-instruct/writing-10k.jsonl
    type: sharegpt.load_ultrachat
  - path: /root/work/chat-regen/chat/llama3.1-8b-instruct/novita20240812.local.jsonl
    type: sharegpt.load_ultrachat
  - path: /root/work/chat-regen/chat/llama3.1-8b-instruct/novita20241118-400K.local.jsonl
    type: sharegpt.load_ultrachat
dataset_prepared_path:

dataset_prepared_path:
val_set_size: 0.05
output_dir: /network/train/llama3/20241211-llama3.2-200M-finetune
auto_resume_from_checkpoints: true

sequence_len: 4096
sample_packing: false
pad_to_sequence_len: true

unfrozen_parameters:
  - model.embed_tokens.
  - model.layers.3.
  - model.norm.

wandb_project: llama3
wandb_entity: k-l-lambda-org
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 4
max_steps: 500000
num_epochs: 100
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true
s2_attention:

warmup_steps: 10
evals_per_epoch: 4
eval_table_size:
eval_max_new_tokens: 128
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<|begin_of_text|>"
  eos_token: "<|end_of_text|>"
  pad_token: "<|end_of_text|>"
